// <auto-generated />
using LMS.Services.SubjectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Services.SubjectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Services.SubjectAPI.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Code = "CS101",
                            Credits = 3,
                            Description = "An introductory course covering the fundamentals of computer science.",
                            Name = "Introduction to Computer Science"
                        },
                        new
                        {
                            SubjectId = 2,
                            Code = "WD200",
                            Credits = 4,
                            Description = "Basic concepts and skills for web development.",
                            Name = "Web Development Basics"
                        },
                        new
                        {
                            SubjectId = 3,
                            Code = "DBMS301",
                            Credits = 3,
                            Description = "Study of database systems and SQL.",
                            Name = "Database Management Systems"
                        },
                        new
                        {
                            SubjectId = 4,
                            Code = "ALGO401",
                            Credits = 4,
                            Description = "Advanced course on algorithm design and analysis.",
                            Name = "Algorithm Design"
                        },
                        new
                        {
                            SubjectId = 5,
                            Code = "SEC101",
                            Credits = 3,
                            Description = "Introduction to cybersecurity principles and practices.",
                            Name = "Cybersecurity Fundamentals"
                        },
                        new
                        {
                            SubjectId = 6,
                            Code = "DS201",
                            Credits = 3,
                            Description = "Study of fundamental data structures.",
                            Name = "Data Structures"
                        },
                        new
                        {
                            SubjectId = 7,
                            Code = "SE401",
                            Credits = 4,
                            Description = "Principles and practices of software engineering.",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            SubjectId = 8,
                            Code = "AI501",
                            Credits = 4,
                            Description = "Exploration of artificial intelligence concepts and techniques.",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            SubjectId = 9,
                            Code = "MAD301",
                            Credits = 3,
                            Description = "Development of mobile applications for various platforms.",
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            SubjectId = 10,
                            Code = "NETSEC401",
                            Credits = 4,
                            Description = "Security aspects of computer networks.",
                            Name = "Network Security"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
