// <auto-generated />
using LMS.Services.StudentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Services.StudentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123054829_AddStudentToDbAndSeedData")]
    partial class AddStudentToDbAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Services.StudentAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            GroupId = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            StudentId = 2,
                            GroupId = 2,
                            Name = "Jack Sparrow"
                        },
                        new
                        {
                            StudentId = 3,
                            GroupId = 3,
                            Name = "Albert Einstein"
                        },
                        new
                        {
                            StudentId = 4,
                            GroupId = 2,
                            Name = "Nikola Tesla"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
