// <auto-generated />
using LMS.Services.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Services.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Services.Shared.Models.GroupSubject", b =>
                {
                    b.Property<int>("GroupSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupSubjectId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("GroupSubjectId");

                    b.ToTable("GroupSubjects");

                    b.HasData(
                        new
                        {
                            GroupSubjectId = 1,
                            GroupId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            GroupSubjectId = 2,
                            GroupId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            GroupSubjectId = 3,
                            GroupId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            GroupSubjectId = 4,
                            GroupId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            GroupSubjectId = 5,
                            GroupId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            GroupSubjectId = 7,
                            GroupId = 1,
                            SubjectId = 10
                        },
                        new
                        {
                            GroupSubjectId = 8,
                            GroupId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            GroupSubjectId = 9,
                            GroupId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            GroupSubjectId = 10,
                            GroupId = 2,
                            SubjectId = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
